# Permalinks
permalink:           /:year/:month/:day/:slug.html

# Setup
title:               'Hop and Fork'
#tagline:             ''
description:         'Open Source team based in University of Rome "Tor Vergata"'
url:                 http://hopandfork.org
baseurl: '' 
gems: [jekyll-paginate, jekyll-feed]
paginate:            5
paginate_path: "page:num"

twitter_username: hopandfork

# Custom vars
version:             1.0.1
