# Permalinks
#
#permalink:           pretty
permalink:           date

# Setup
title:               'Hop and Fork'
#tagline:             ''
description:         'Open Source team based in University of Rome "Tor Vergata"'
url:                 https://hopandfork.github.io
baseurl: '' 
gems: [jekyll-paginate, jekyll-feed]
paginate:            5
paginate_path: "page:num"


# Custom vars
version:             1.0.0
